### ISSUE TITLE
Is there a plan to change the API and implement into instance/object oriented pattern?

### ISSUE THREAD

**Issue by faywong** [inanevin/LinaVG#4]

**Comment by inanevin** [comment]
Currently there are no plans to do so, as I still would like to keep the immediate-mode GUI drawing aspect of LinaVG. Also other considerations such as parent-child relations, alignments and such should be taken into account when we talk about object-oriented GUI design. 

For now, I also want to keep LinaVG as a use-for-anything kind of a tool, not specifically for drawing GUIs. That's why I plan to keep the API as open as possible.

That being said, of course I am open to suggestions and discussion regarding this. Currently it's very much possible to write a wrapper library around LinaVG to create a custom object-oriented GUI system.
